//公共
export const GET_ABOUT_ME = 'GET_ABOUT_ME'
export const GET_RECOMMAND_LIST = 'GET_RECOMMAND_LIST'
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const GET_ARTICLE_LABEL = 'GET_ARTICLE_LABEL'
export const GET_MEMO_LIST = 'GET_MEMO_LIST'
export const GET_MEMO_ITEM = 'GET_MEMO_ITEM'
export const GIVE_RECOMMAND_TEXT = 'GIVE_RECOMMAND_TEXT'